CREATE TABLE [dbo].[Table]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [TTBR1] INT NULL, 
    [TTBR2] INT NULL, 
    [TTBR3] INT NULL, 
    [TTBL1] INT NULL, 
    [TTBL2] INT NULL, 
    [TTBL3] INT NULL, 
    [TTFR1] INT NULL, 
    [TTFR2] INT NULL, 
    [TTFR3] INT NULL, 
    [TTFL1] INT NULL, 
    [TTFL2] INT NULL, 
    [TTFL3] INT NULL, 
    [MT1] INT NULL, 
    [MT2] INT NULL, 
    [WSBR] INT NULL, 
    [WSBL] INT NULL, 
    [WSFR] INT NULL, 
    [WSFL] INT NULL, 
    [throttleR] INT NULL, 
    [throttleL] INT NULL, 
    [packVoltage] INT NULL, 
    [packCurrent] INT NULL, 
    [packTemperature] INT NULL, 
    [steeringAngle] INT NULL, 
    [accelAngle] INT NULL, 
    [brakeAngle] INT NULL
)
